export const LEGAL_CONTENT = {
    privacy: {
        title: "Privacy Policy",
        content: `**Last updated:** December 23, 2024

Welcome to **Prank-Z**. Your privacy is important to us. This Privacy Policy explains how we collect, use, and protect your information when you use our website and services.

## 1. Information We Collect

We may collect the following information:

* Email address (for account creation, subscriptions, and support)
* Uploaded images (used solely for image generation)
* Usage data (number of generations, feature usage)
* Payment and billing data (processed securely by Paddle)

## 2. How We Use Your Information

We use your information to:

* Provide and operate the Prank-Z service
* Process subscriptions and payments
* Enforce usage limits and credits
* Improve product performance and user experience
* Provide customer support

## 3. Image Data

Uploaded images are processed to generate prank-style AI edits. Images may be temporarily stored to provide the service and are automatically deleted after processing or within a limited retention period. We do not sell or share uploaded images with third parties.

## 4. Payments

All payments are securely processed by **Paddle**. Prank-Z does not store or have access to your full payment information.

## 5. Cookies

We may use cookies or similar technologies to maintain sessions, improve performance, and analyze traffic.

## 6. Data Security

We take reasonable technical and organizational measures to protect your data. However, no online service can guarantee absolute security.

## 7. Your Rights

You may request access, correction, or deletion of your personal data by contacting us at our support email.

## 8. Changes

We may update this Privacy Policy from time to time. Continued use of the service constitutes acceptance of the updated policy.

## 9. Contact

For privacy-related questions, contact us at: **prankz.web@gmail.com**`
    },
    terms: {
        title: "Terms of Service",
        content: `**Last updated:** December 23, 2024

These Terms & Conditions govern the use of Prank-Z, operated by Ahadbek Axmatqulov (sole proprietor).

By accessing or using **Prank-Z**, you agree to these Terms of Service.

## 1. Service Description

Prank-Z is an AI-powered web application that allows users to upload photos and apply humorous, prank-style AI edits for entertainment purposes only.

## 2. Eligibility

You must be at least 13 years old to use Prank-Z. Users under 18 must have parental consent.

## 3. User Responsibilities

You agree that:

* You own or have permission to use uploaded images
* You will not upload illegal, harmful, violent, or non-consensual content
* You will not use Prank-Z to harass, defame, or harm others

## 4. Content Ownership

You retain ownership of the images you upload. Prank-Z does not claim ownership over user content.

## 5. AI-Generated Content Disclaimer

All outputs are automatically generated by AI and provided **as-is**. Prank-Z does not guarantee accuracy, realism, or appropriateness of generated images.

## 6. Subscriptions & Credits

Some features require a paid subscription. Image generation is limited by credits. Credits reset according to the subscription plan and cannot be carried over unless stated.

## 7. Refund Policy

Due to the digital nature of the service, refunds are generally not provided once credits are used. Refund requests may be considered within 7 days if no significant usage has occurred.

## 8. Termination

We reserve the right to suspend or terminate accounts that violate these Terms.

## 9. Limitation of Liability

Prank-Z shall not be liable for any damages resulting from misuse of the service or generated content.

## 10. Changes

We may update these Terms at any time. Continued use constitutes acceptance.`
    },
    refund: {
        title: "Refund Policy",
        content: `Prank-Z offers digital services with immediate access. As such:

* No refunds after credits are used
* Refunds may be considered within 7 days of purchase if usage is minimal
* All refund requests must be submitted via email`
    },
    acceptable_use: {
        title: "Acceptable Use Policy",
        content: `You agree not to use Prank-Z to:

* Create or distribute illegal or harmful content
* Violate privacy or intellectual property rights
* Harass, threaten, or impersonate others
* Generate content involving hate, violence, or sexual exploitation

Violations may result in account suspension or termination.`
    },
    disclaimer: {
        title: "Disclaimer",
        content: `Prank-Z is built for entertainment and humor only. Do not use generated content to deceive, harm, or manipulate others. Use responsibly.`
    },
    contact: {
        title: "Contact Us",
        content: `If you have any questions, concerns, or feedback about Prank-Z, please don't hesitate to reach out to us.
        
**Email:** prankz.web@gmail.com`
    }
};

export type LegalDocKey = keyof typeof LEGAL_CONTENT;
